# .rubocop.yml

AllCops:
  TargetRubyVersion: 3.2.1
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 20
