new_topic_response = {"id"=>1339,
  "username"=>"scossar",
  "avatar_template"=>"/user_avatar/127.0.0.1/scossar/{size}/57_2.png",
  "created_at"=>"2024-06-08T21:47:20.833Z",
  "cooked"=>"<p>It’s a minor thing, but it comes up a lot. I’ll do some tests.</p>\n<p>Copying from Alacritty:</p>\n<pre><code class=\"lang-auto\">~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ set test this is a test\n\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ echo $test\nthis is a test\n</code></pre>\n<p>I was able to copy that text in normal mode (Vim keybindings) by highlighting the text with the mouse, then selecting it with <code>Ctrl+Shift+C</code>. That’s kind of awkward, but maybe it’s good enough.</p>\n<p>Starting a Zellij session:</p>\n<pre data-code-wrap=\"txt\"><code class=\"lang-txt\">~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ set test this is a test\n\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ echo $test\nthis is a test\n</code></pre>\n<p>I was also able to copy that text with <code>Ctrl+Shift+C</code> in normal mode.</p>\n<p>Entering “search” mode on Zellij: <code>Ctrl+s</code> then <code>e</code></p>\n<pre data-code-wrap=\"txt\"><code class=\"lang-txt\">~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n</code></pre>\n<p>Nothing’s changed. The <code>Ctrl+Shift+C</code> command still works.</p>\n<p>Running Neovim in a Zellij session:</p>\n<pre data-code-wrap=\"ts\"><code class=\"lang-ts\">import { App, Editor, MarkdownView, Modal, Plugin } from \"obsidian\";\nimport { DiscoursePluginSettings, DiscourseSettingTab } from \"./settings\";\nimport { publishToDiscourse } from \"./publish\";\n\nexport default class DiscoursePlugin extends Plugin {\n\tsettings: DiscoursePluginSettings;\n\n\tasync onload() {\n\t\tawait this.loadSettings();\n\n\t\tthis.registerEvent(\n\t\t\tthis.app.workspace.on(\"editor-menu\", (menu, editor, view) =&gt; {\n\t\t\t\tmenu.addItem((item) =&gt; {\n\t\t\t\t\titem.setTitle(\"Publish to Discourse\")\n\t\t\t\t\t\t.setIcon(\"send-horizontal\")\n\n</code></pre>\n<p>Text selected in visual mode and yanked with <code>y</code> gets added to the system clipboard.</p>\n<p>This is good enough for now.</p>",
  "post_number"=>1,
  "post_type"=>1,
  "updated_at"=>"2024-06-08T21:47:20.833Z",
  "reply_count"=>0,
  "reply_to_post_number"=>nil,
  "quote_count"=>0,
  "incoming_link_count"=>0,
  "reads"=>0,
  "readers_count"=>0,
  "score"=>0,
  "yours"=>true,
  "topic_id"=>683,
  "topic_slug"=>"copying-text-to-the-system-clipboard",
  "primary_group_name"=>"customer_support",
  "flair_name"=>"customer_support",
  "flair_url"=>nil,
  "flair_bg_color"=>"",
  "flair_color"=>"",
  "flair_group_id"=>41,
  "version"=>1,
  "can_edit"=>true,
  "can_delete"=>false,
  "can_recover"=>false,
  "can_see_hidden_post"=>true,
  "can_wiki"=>true,
  "user_title"=>"Supporter",
  "title_is_group"=>true,
  "bookmarked"=>false,
  "raw"=>"It's a minor thing, but it comes up a lot. I'll do some tests.\n\nCopying from Alacritty:\n\n```\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ set test this is a test\n\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ echo $test\nthis is a test\n```\n\nI was able to copy that text in normal mode (Vim keybindings) by highlighting the text with the mouse, then selecting it with `Ctrl+Shift+C`. That's kind of awkward, but maybe it's good enough.\n\nStarting a Zellij session:\n\n```txt\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ set test this is a test\n\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n❯ echo $test\nthis is a test\n```\n\nI was also able to copy that text with `Ctrl+Shift+C` in normal mode. \n\nEntering \"search\" mode on Zellij: `Ctrl+s` then `e`\n\n```txt\n~ on  main [?] via  v20.14.0 via 🐘 v8.3.7 via 🐍 v3.11.2 via 💎 v3.2.1\n```\n\nNothing's changed. The `Ctrl+Shift+C` command still works.\n\nRunning Neovim in a Zellij session:\n\n```ts\nimport { App, Editor, MarkdownView, Modal, Plugin } from \"obsidian\";\nimport { DiscoursePluginSettings, DiscourseSettingTab } from \"./settings\";\nimport { publishToDiscourse } from \"./publish\";\n\nexport default class DiscoursePlugin extends Plugin {\n\tsettings: DiscoursePluginSettings;\n\n\tasync onload() {\n\t\tawait this.loadSettings();\n\n\t\tthis.registerEvent(\n\t\t\tthis.app.workspace.on(\"editor-menu\", (menu, editor, view) => {\n\t\t\t\tmenu.addItem((item) => {\n\t\t\t\t\titem.setTitle(\"Publish to Discourse\")\n\t\t\t\t\t\t.setIcon(\"send-horizontal\")\n\n```\n\nText selected in visual mode and yanked with `y` gets added to the system clipboard. \n\nThis is good enough for now.",
  "actions_summary"=>[{"id"=>7, "can_act"=>true},
  {"id"=>3, "can_act"=>true},
  {"id"=>4, "can_act"=>true},
  {"id"=>8, "can_act"=>true},
  {"id"=>10, "can_act"=>true}],
  "moderator"=>false,
  "admin"=>true,
  "staff"=>true,
  "user_id"=>7,
  "draft_sequence"=>0,
  "hidden"=>false,
  "trust_level"=>4,
  "deleted_at"=>nil,
  "user_deleted"=>false,
  "edit_reason"=>nil,
  "can_view_edit_history"=>true,
  "wiki"=>false,
  "reviewable_id"=>nil,
  "reviewable_score_count"=>0,
  "reviewable_score_pending_count"=>0,
  "mentioned_users"=>[],
  "event"=>nil,
  "calendar_details"=>[],
  "reactions"=>[],
  "current_user_reaction"=>nil,
  "reaction_users_count"=>0,
  "current_user_used_main_reaction"=>false,
  "can_accept_answer"=>false,
  "can_unaccept_answer"=>false,
  "accepted_answer"=>false,
  "topic_accepted_answer"=>false,
  "can_vote"=>false}
